name: Scrape latest data

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out this repo'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Block concurrent executions'
      uses: softprops/turnstyle@v1
      with:
        poll-interval-seconds: 20
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Fetch latest data'
      run: |-
        curl "https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/votes-remaining-page/national/president.json" | jq . > results.json

    - name: 'Commit fresh data from NYT or ignore'
      run: |-
        git config user.name "Hubot"
        git config user.email "hubot@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
  
    - name: 'Set up Python 3.8'
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: 'Install Python requirements'
      run: |-
        python -m pip install -U pip
        pip install -r requirements.txt

    - name: 'Generate battleground-state-changes.<txt/html/csv>'
      run: |-
        ./print-battleground-state-changes

    - name: 'Commit fresh changes or ignore'
      run: |-
        git config user.name "Hubot"
        git config user.email "hubot@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Regenerate battleground-state-changes.<txt/html/csv>" || exit 0
        git push
